### PR TITLE
fix for firefox

### PR DESCRIPTION
**Pull request by jakubsikora**
Firefox doesn't have event.offsetX and event.offsetY which causing issues with colorpicker. This extra case fixing the problem in FF.

### CODE REVIEW

**Comment by HHogg** [comment]
:+1:

**Comment by foreachlt** [comment]
:+1:

**Comment by OrganicPanda** [comment]
:+1:

**Comment by rvijayan** [comment]
:+1:

**Comment by buberdds** [comment]
I had to remove your prevoius commit. This one is not working correctly in browsers too. Can you please validate if your fixes are working correctly in FF and IE too? thanks

**Comment by jakubsikora** [comment]
@buberdds sorry man. I can't do primary math apparently :) It should work now. Tested on IE10/11, FF, and Chrome.

**Comment by foreachlt** [comment]
@jakubsikora maybe you could also include a test: https://github.com/buberdds/angular-bootstrap-colorpicker/blob/master/test/unit/colorpickerSpec.js :wink:

**Comment by buberdds** [comment]
np @jakubsikora, thanks for another update. I will test it asap

**Pull request merged**
