### PR TITLE
added on selected handler

### PR DESCRIPTION
**Pull request by ste2425**
Added the ability to specify an 'On Selected' handler to be called when the user selects a colour.

### CODE REVIEW

**Comment by buberdds** [comment]
Yes, it will dispatch an event upwards through the scope. If this is a problem? I think it depends where you gonna attach listeners (structure of scope hierarchy) and in that event you will find data and event object so it's easy to check which color picker was used.

I would like to avoid adding 'handlers' because we might need many, like: onchange, onselect, onopen etc.

**Comment by ste2425** [comment]
That is true with the possibility for many handlers. No problem, ill re-factor and be back.

**Comment by ste2425** [comment]
Sorry about this, first time ive done a PR on git hub. I had my git config set up for my work account, but didn't realise till i committed and pushed the re-work. So i deleted the fork, then forked again and made the changes etc. I didn't know that this would effectively break this PR. Is it possible to modify this PR for the new fork and commit or would i have to submit a new one?

**Comment by buberdds** [comment]
hey, you will have to revert first commit (01aeff5) from this PR, there is still $parse in DI etc. So at the end it's gonna be safer for both of us to create a new PR and move/cherry pick only 5fbb5b6 commit

thank you for your work

**Comment by buberdds** [comment]
moved to  #85

**Pull request closed without merging**
