### PR TITLE
Fix for issue #93 related to Firefox

### PR DESCRIPTION
**Pull request by llattes**
- Added polyfills for offsetX and offsetY. When event.offsetX cannot be resolved, the polyfill calculates its value.
- Included Firefox launcher in Karma tests.

### CODE REVIEW

**Comment by buberdds** [comment]
These are jQuery methods, right?

**Comment by llattes** [comment]
Yes, found there is an issue related to offsets in FF in jQuery bugs tracker: http://bugs.jquery.com/ticket/8523#comment:14

**Comment by buberdds** [comment]
Ok, thanks, but can't merge this PR. The trick is to fix this issue without adding additional dependencies like jQuery.

**Comment by llattes** [comment]
I found a way that uses no additional dependencies. Do you mind if I send a new pull request?

**Comment by buberdds** [comment]
yeah of course, it would be great!

**Pull request closed without merging**
